services:
  mysql:
    image: mysql:8.0
    container_name: ms2_mysql
    environment:
      MYSQL_ROOT_PASSWORD: readme123
      MYSQL_DATABASE: ms2_books
      MYSQL_USER: readme
      MYSQL_PASSWORD: readme123
    ports:
      - "3306:3306"
    volumes:
      - ms2_mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ms2_mysqldata:
